AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  FastAPI in Zip

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Resources:
  FastAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: run.sh
      Runtime: python3.10
      MemorySize: 256
      Environment:
        Variables:
          AWS_LAMBDA_EXEC_WRAPPER: /opt/bootstrap
          PORT: "8000"
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:753240598075:layer:LambdaAdapterLayerX86:20
        - !Ref FastAPILayer
      Events:
        ApiEvent:
          Type: HttpApi
  FastAPILayer:
    Type: AWS::Serverless::LayerVersion
    Metadata:
      BuildMethod: makefile
      BuildArchitecture: x86_64
    Properties:
      Description: FastAPI Layer
      ContentUri: .
      CompatibleArchitectures:
        - x86_64
      CompatibleRuntimes:
        - python3.10
      RetentionPolicy: Delete

Outputs:
  FastAPIApi:
    Description: "API Gateway endpoint URL for Prod stage for FastAPI function"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/"
  FastAPIFunction:
    Description: "FastAPI Lambda Function ARN"
    Value: !GetAtt FastAPIFunction.Arn
  FastAPIIamRole:
    Description: "Implicit IAM Role created for FastAPI function"
    Value: !GetAtt FastAPIFunctionRole.Arn
